version: '3.7'

services:
  api:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      .env
    depends_on:
      - primary_db


  primary_db:
    image: postgres:13.0-alpine
    volumes:
      - primary_data:/var/lib/postgresql/data/
    env_file:
      .env



volumes:
  primary_data: