# Generated by Django 4.2 on 2023-04-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "example_field1",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "example_field2",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "example_field3",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "example_field4",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "example_field5",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "example_field6",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "example_field7",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "example_field8",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "example_field9",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "example_field10",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "example_field11",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "example_field1",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "example_field2",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "example_field3",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "example_field4",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "example_field5",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "example_field6",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "example_field7",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "example_field8",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "example_field9",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "example_field10",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "example_field11",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
            ],
        ),
    ]
