# Generated by Django 4.1.7 on 2023-04-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='example_field10',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='example_field11',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='example_field12',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='example_field13',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='example_field14',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='example_field15',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='example_field3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='example_field4',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='example_field5',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='example_field6',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='example_field7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='example_field8',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='example_field9',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='example_field10',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='example_field11',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='example_field12',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='example_field13',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='example_field14',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='example_field15',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='example_field3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='example_field4',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='example_field5',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='example_field6',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='example_field7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='example_field8',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='example_field9',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
