# Generated by Django 4.2 on 2023-04-03 21:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("ae779a8f-6b16-49b5-a0ae-325f2ba36b49"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("instance_type", models.CharField(max_length=250)),
                ("instance_id", models.IntegerField()),
                ("previos_state", models.JSONField()),
                ("actual_state", models.JSONField()),
                ("author", models.CharField(max_length=250)),
                ("created", models.DateTimeField()),
            ],
        ),
    ]
