# Generated by Django 4.2 on 2023-04-04 18:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("8e1104ed-51fc-4f8f-9ed2-3d3707ba4f3c"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("instance_type", models.CharField(max_length=250)),
                ("instance_id", models.IntegerField()),
                ("previous_state", models.JSONField()),
                ("actual_state", models.JSONField()),
                ("author", models.CharField(max_length=250)),
                ("created", models.DateTimeField()),
            ],
        ),
    ]
